package io.diplom.exception

class ExistException() : GeneralException("Пользователь с таким логином или номером телефона уже существует", 409)
